/**
  **********************************************************************************
  * BUTTON DRIVER - DIGILOG CONSOLE
  **********************************************************************************
  * @file button_driver.c
  * @brief Reads one push button's level out of the MCP23017 cache.
  *
  * @author Darya Petrova (petrov.da@northeastern.edu)
  *
  * @note Doc banner generated by Claude (Opus 5) from the source at `6aa52bb`; not
  *       author-written and not yet author-reviewed. Code authorship is unchanged.
  *       Delete this note once an author has reviewed it.
  **********************************************************************************
*/
#include <stdbool.h>

#include "hardware_drivers/button_driver.h"

bool get_button_state (button_info_t *info)
{
    uint8_t gpio_bits[2];
    mcp23017_read_from_cache(info->bus, info->addr, gpio_bits);
    if (info->port == MCP_GPIOA)
        return (gpio_bits[0] >> info->pin) & 1;
    else
        return (gpio_bits[1] >> info->pin) & 1;
}

