/**
  **********************************************************************************
  * MOTORIZED FADER DRIVER - DIGILOG CONSOLE
  **********************************************************************************
  * @file fader_driver.c
  * @brief Proportional control law driving a motorized fader toward a target position, with
  *        the motor released while the fader is being touched.
  *
  * @warning Not functional. get_physical_fader_position() and is_fader_touched() are
  *          non-void with no return statement - undefined behaviour, not merely a TODO -
  *          and update_motor_power() is a no-op. init_fader() is an empty body with its
  *          ADC calibration call commented out. No PWM is ever started.
  *
  * @author Darya Petrova (petrov.da@northeastern.edu)
  *
  * @note Doc banner generated by Claude (Opus 5) from the source at `d85f17a`; not
  *       author-written and not yet author-reviewed. Code authorship is unchanged.
  *       Delete this note once an author has reviewed it.
  **********************************************************************************
*/
#include <stdbool.h>
#include <stdint.h>
#include "hardware_drivers/fader_driver.h"
#include "stm32g4xx_hal_adc_ex.h"

#define FADER_POWER_COEFFICIENT 4

static uint16_t get_physical_fader_position (fader_info_t *info)
{
    // TODO
}

static bool is_fader_touched (fader_info_t *info)
{
    // TODO
}

static void update_motor_power (int32_t power){
    // TODO
}

static inline int32_t clamp_mult (int32_t a, int32_t b)
{
    int32_t x = a * b;
    if (a != 0 && x / a != b)
    {
        if (a > 0 && b > 0)
        {
            return INT32_MAX;
        }
        if (a < 0 && b < 0)
        {
            return INT32_MAX;
        }
        return INT32_MIN;
    }
    return x;
}

/**
 * @brief Feedback control based on motor target and position
 * Feedback control to move the motor towards a target position;
 * currently just uses proportional deviation with no derivative or integral
 */
static int32_t get_motor_power (fader_info_t *info, fader_state_t *state)
{
    const int32_t where_it_is = get_physical_fader_position(info);
    const int32_t where_it_isnt = state->position;

    const int32_t deviation = where_it_isnt - where_it_is;
    return clamp_mult(deviation, FADER_POWER_COEFFICIENT);
}

void update_fader (fader_info_t *info, fader_state_t *old_state, fader_state_t *new_state)
{
    fader_state_t new_state_i = *old_state;
    if (is_fader_touched(info))
    {
        new_state_i.movement_mode = FADER_UNPOWERED;
        new_state_i.position = get_physical_fader_position(info);
    }
    else
    {
        new_state_i.movement_mode = FADER_MOVE_OR_HOLD_TARGET;
        update_motor_power(get_motor_power(info, &new_state_i));
    }

    *new_state = new_state_i;
}

void init_fader(fader_info_t *info){
    //HAL_ADCEx_Calibration_Start(info->adc, ADC_SINGLE_ENDED);
    // TODO
}
