/**
  **********************************************************************************
  * BUTTON CONTROL - PRIVATE HEADER - DIGILOG CONSOLE
  **********************************************************************************
  * @file button_control.h
  * @brief Internal to control_integration. Not on the public include path.
  *
  * @author Darya Petrova (petrov.da@northeastern.edu)
  *
  * @note Doc banner generated by Claude (Opus 5) from the source at `6aa52bb`; not
  *       author-written and not yet author-reviewed. Code authorship is unchanged.
  *       Delete this note once an author has reviewed it.
  **********************************************************************************
*/
#ifndef BUTTON_CONTROL_H
#define BUTTON_CONTROL_H

/**
 * This header file is internal to control_integration, separated for organization.
 * It should not have to be included anywhere outside of control_integration; it is not a public header
 */

#include "control_integration/control_interface.h"
#include "hardware_sets.h"
#include "hardware_state_sets.h"

void init_button_controls(uint8_t channel, channel_control_io_state *state, channel_control_io_t *io);
void update_channel_button_values (channel_controls *vals, channel_control_io_state *state, channel_control_io_t *io);
void update_channel_button_leds (channel_controls *vals, channel_control_io_state *state, channel_control_io_t *io);

#endif
