/**
  **********************************************************************************
  * BUTTON CONTROL - DIGILOG CONSOLE
  **********************************************************************************
  * @file button_control.c
  * @brief Edge-detects push buttons and toggles the corresponding console values.
  *
  * @warning Not wired up. init_button_controls() is an empty body, so the
  *          button_info_t that update_channel_button_values() reads is never
  *          populated; update_channel_button_leds() is an empty stub.
  *
  * @author Darya Petrova (petrov.da@northeastern.edu)
  *
  * @note Doc banner generated by Claude (Opus 5) from the source at `d85f17a`; not
  *       author-written and not yet author-reviewed. Code authorship is unchanged.
  *       Delete this note once an author has reviewed it.
  **********************************************************************************
*/
#include "button_control.h"
#include "control_integration/control_interface.h"
#include "hardware_drivers/button_driver.h"
#include "hardware_sets.h"
#include "hardware_state_sets.h"
#include "portmacro.h"

static void update_toggle_button_val_from_info (
    SemaphoreHandle_t *out_mutex,
    button_state_t *btn_state,
    button_info_t *info,
    bool *val_out //
)
{
    bool new_button_state = get_button_held(info);

    if (new_button_state && !(btn_state->held))
    {
        xSemaphoreTake(*out_mutex, portMAX_DELAY);
        *val_out = !*val_out;
        xSemaphoreGive(*out_mutex);
        btn_state->press_countdown = DOUBLE_PRESS_TIME;
    }

    btn_state->held = new_button_state;
}

static inline void update_button_timer (button_state_t *btn_state)
{
    if (btn_state->press_countdown == 0)
    {
        return;
    }
    btn_state->press_countdown--;
}

void init_button_controls (uint8_t channel, channel_control_io_state *state, channel_control_io_t *io)
{
    // TODO: Fill channel_controls_io to match the hardware, and set initial states
}

void update_channel_button_leds (
    SemaphoreHandle_t *vals_mutex,
    channel_controls *vals,
    channel_control_io_state *state,
    channel_control_io_t *io
)
{
}

void update_channel_button_values (
    SemaphoreHandle_t *vals_mutex,
    channel_controls *vals,
    channel_control_io_state *state,
    channel_control_io_t *io
)
{
    update_button_timer(&(state->mute_button_state));
    update_toggle_button_val_from_info(vals_mutex, &(state->mute_button_state), &(io->mute_button.button), &(vals->muted));

    // TODO: Do this for the rest of the toggle-buttons on the channel
    // TODO: handle non-toggle (e.g radio) buttons
}
