/**
  **********************************************************************************
  * BUTTON CONTROL - DIGILOG CONSOLE
  **********************************************************************************
  * @file button_control.c
  * @brief Edge-detects push buttons and toggles the corresponding console values.
  *
  * @warning Not wired up. init_button_controls() is an empty body, so the
  *          button_info_t that update_channel_button_values() reads is never
  *          populated; update_channel_button_leds() is an empty stub.
  *
  * @author Darya Petrova (petrov.da@northeastern.edu)
  *
  * @note Doc banner generated by Claude (Opus 5) from the source at `6aa52bb`; not
  *       author-written and not yet author-reviewed. Code authorship is unchanged.
  *       Delete this note once an author has reviewed it.
  **********************************************************************************
*/
#include "button_control.h"
#include "control_integration/control_interface.h"
#include "hardware_drivers/button_driver.h"
#include "hardware_sets.h"
#include "hardware_state_sets.h"

static void update_toggle_button_val_from_info (bool *btn_state, button_info_t *info, bool *val_out)
{
    bool new_button_state = get_button_state(info);

    if (new_button_state && !*btn_state)
    {
        *val_out = !*val_out;
    }

    *btn_state = new_button_state;
}

void init_button_controls (uint8_t channel, channel_control_io_state *state, channel_control_io_t *io)
{
    // TODO: Fill channel_controls_io to match the hardware, and set initial states
}

void update_channel_button_leds (channel_controls *vals, channel_control_io_state *state, channel_control_io_t *io) {}

void update_channel_button_values (channel_controls *vals, channel_control_io_state *state, channel_control_io_t *io)
{
    update_toggle_button_val_from_info(&(state->mute_button_state), &(io->mute_button.button), &(vals->muted));

    // TODO: Do this for the rest of the toggle-buttons on the channel
    // TODO: handle non-toggle (e.g radio) buttons
}
