/**
  **********************************************************************************
  * FADER CONTROL - PRIVATE HEADER - DIGILOG CONSOLE
  **********************************************************************************
  * @file fader_control.h
  * @brief Internal to control_integration. Not on the public include path.
  *
  * @author Darya Petrova (petrov.da@northeastern.edu)
  *
  * @note Doc banner generated by Claude (Opus 5) from the source at `cc3d3a1`; not
  *       author-written and not yet author-reviewed. Code authorship is unchanged.
  *       Delete this note once an author has reviewed it.
  **********************************************************************************
*/
#ifndef FADER_CONTROL_H
#define FADER_CONTROL_H

#include "hardware_state_sets.h"
#include "hardware_sets.h"

/*
 * This header file is internal to control_integration, separated for organization.
 * It should not have to be included anywhere outside of control_integration; it is not a public header
 */

void init_fader_controls (uint8_t channel, channel_control_io_state *state, channel_control_io_t *io);
void update_channel_fader_hardware (channel_control_io_state *state, channel_control_io_t *io);
void update_channel_fader_values (SemaphoreHandle_t *vals_mutex, channel_controls *vals, channel_control_io_state *state, channel_control_io_t *io);

#endif
