/**
  **********************************************************************************
  * FADER CONTROL - DIGILOG CONSOLE
  **********************************************************************************
  * @file fader_control.c
  * @brief Maps between the fader driver's raw position and the channel's output_gain scalar.
  *
  * @warning Not wired up. init_fader_controls() still assigns `(fader_info_t){}`, which
  *          now zero-initializes the real port/pin/ADC fields rather than an empty
  *          struct - so every fader points at port NULL, pin 0.
  *
  * @author Darya Petrova (petrov.da@northeastern.edu)
  *
  * @note Doc banner generated by Claude (Opus 5) from the source at `d85f17a`; not
  *       author-written and not yet author-reviewed. Code authorship is unchanged.
  *       Delete this note once an author has reviewed it.
  **********************************************************************************
*/
#include "fader_control.h"
#include "control_integration/control_interface.h"
#include "hardware_drivers/fader_driver.h"
#include "hardware_state_sets.h"
#include "hardware_sets.h"
#include "portmacro.h"
#include <stdint.h>

static inline s_scalar_control_t uint16_to_s_scalar (uint16_t in)
{
    return (s_scalar_control_t)(in ^ 0x8000); // XOR MSB
}
static inline uint16_t s_scalar_to_uint16 (s_scalar_control_t in)
{
    return (uint16_t)(in ^ 0x8000); //XOR MSB
}

void update_channel_fader_hardware (channel_control_io_state *state, channel_control_io_t *io)
{
    update_fader(&(io->fader), &(state->fader_state), &(state->fader_state));
}

void update_channel_fader_values (SemaphoreHandle_t *vals_mutex, channel_controls *vals, channel_control_io_state *state, channel_control_io_t *io)
{
    // TODO: Try to find a way to be more conservative about taking the mutex (only take it if values have changed?)
    xSemaphoreTake(*vals_mutex, portMAX_DELAY);
    if (state->fader_state.movement_mode == FADER_UNPOWERED)
    {
        vals->output_gain = uint16_to_s_scalar(state->fader_state.position);
    }
    else
    {
        state->fader_state.position = s_scalar_to_uint16(vals->output_gain);
    }
    xSemaphoreGive(*vals_mutex);
}

void init_fader_controls (uint8_t channel, channel_control_io_state *state, channel_control_io_t *io)
{
    io->fader = (fader_info_t){}; // TODO
    state->fader_state = DEFAULT_FADER_STATE;
}
