var searchData=
[
  ['a_20coord_20and_20use_20render_5fval_0',['Unpack the params inside a knob at a coord and use render_val.',['../led__driver_8c.html#autotoc_md65',1,'']]],
  ['a_20knob_20at_20a_20coord_20and_20use_20render_5fval_1',['Unpack the params inside a knob at a coord and use render_val.',['../led__driver_8c.html#autotoc_md65',1,'']]],
  ['a_20knob_20in_20frame_20buffer_2',['PUBLIC knob_raw : Put arbitrary 32 bits to a knob in frame buffer',['../led__driver_8c.html#autotoc_md77',1,'']]],
  ['a_20knob_20s_20display_20value_3',['Incerment/decrement a knob&apos;s display value.',['../led__driver_8c.html#autotoc_md71',1,'']]],
  ['a_20knob_20s_20display_20value_20specify_20which_20knob_20by_20coords_20chnl_20and_20knob_20number_4',['Change a knob&apos;s display value, specify which knob by coords (chnl and knob number)',['../led__driver_8c.html#autotoc_md69',1,'']]],
  ['a_20knob_20s_20value_20into_20the_20set_20of_20bits_20that_20show_20that_20value_5',['Directly render: turns a knob&apos;s value into the set of bits that show that value',['../led__driver_8c.html#autotoc_md63',1,'']]],
  ['a_20single_20bit_20out_6',['INTERNAL shift_bit : uint32 -&amp;gt; Shifts a single bit out.',['../led__driver_8c.html#autotoc_md57',1,'']]],
  ['a_20specific_20button_20display_20led_20by_20coordinate_7',['Set a specific button display LED by coordinate',['../led__driver_8c.html#autotoc_md79',1,'']]],
  ['a_20specified_20knob_8',['a specified knob',['../led__driver_8c.html#autotoc_md85',1,'PUBLIC knob_get_disp : returns the display mode (knob_scale_t type) of a specified knob'],['../led__driver_8c.html#autotoc_md87',1,'PUBLIC knob_get_scale : returns the scale mode (knob_scale_t type) of a specified knob']]],
  ['a_20whole_20channel_20s_20button_20leds_20at_20once_9',['Sets a whole channel&apos;s button LEDs at once',['../led__driver_8c.html#autotoc_md81',1,'']]],
  ['active_20low_20so_20higher_20brightness_20needs_20less_20high_20time_20on_20pwm_10',['OE is active low so higher brightness needs less high time on PWM.',['../led__driver_8c.html#autotoc_md99',1,'']]],
  ['all_20animation_20phases_11',['all animation phases',['../led__driver_8c.html#autotoc_md41',1,'resets all animation phases'],['../led__driver_8c.html#autotoc_md109',1,'resets all animation phases']]],
  ['all_20led_20states_20to_20off_20and_20latch_12',['PUBLIC led_clear : Set all led states to off and latch',['../led__driver_8c.html#autotoc_md97',1,'']]],
  ['all_20leds_20externally_13',['PUBLIC led_brightness : Set the brightness of all LEDs externally.',['../led__driver_8c.html#autotoc_md101',1,'']]],
  ['an_20entire_20frame_20of_20led_20bits_20out_20end_20sent_20first_14',['INTERNAL frame_out : Sends an entire frame of LED bits out, end sent first',['../led__driver_8c.html#autotoc_md61',1,'']]],
  ['and_20call_20anim_5fstop_15',['When loading done just stop and call anim_stop.',['../led__driver_8c.html#autotoc_md113',1,'']]],
  ['and_20claim_20display_16',['PUBLIC anim_claim : stop what was running and claim display',['../led__driver_8c.html#autotoc_md111',1,'']]],
  ['and_20copies_20them_20out_17',['Range checks external knob/channel coords and copies them out',['../led__driver_8c.html#autotoc_md67',1,'']]],
  ['and_20knob_20number_18',['Change a knob&apos;s display value, specify which knob by coords (chnl and knob number)',['../led__driver_8c.html#autotoc_md69',1,'']]],
  ['and_20latch_19',['PUBLIC led_clear : Set all led states to off and latch',['../led__driver_8c.html#autotoc_md97',1,'']]],
  ['and_20use_20render_5fval_20',['Unpack the params inside a knob at a coord and use render_val.',['../led__driver_8c.html#autotoc_md65',1,'']]],
  ['anim_5fclaim_20_3a_20stop_20what_20was_20running_20and_20claim_20display_21',['PUBLIC anim_claim : stop what was running and claim display',['../led__driver_8c.html#autotoc_md111',1,'']]],
  ['anim_5fstop_22',['When loading done just stop and call anim_stop.',['../led__driver_8c.html#autotoc_md113',1,'']]],
  ['animation_20matches_20the_20mode_23',['center mode the animation matches the mode.',['../led__driver_8c.html#autotoc_md115',1,'']]],
  ['animation_20phases_24',['animation phases',['../led__driver_8c.html#autotoc_md41',1,'resets all animation phases'],['../led__driver_8c.html#autotoc_md109',1,'resets all animation phases']]],
  ['arbitrary_2032_20bits_20to_20a_20knob_20in_20frame_20buffer_25',['PUBLIC knob_raw : Put arbitrary 32 bits to a knob in frame buffer',['../led__driver_8c.html#autotoc_md77',1,'']]],
  ['are_20currently_20on_20in_20normal_20state_20will_20do_20it_20mode_201_20every_20single_20led_20does_20it_26',['are currently on in normal state will do it mode 1 every single LED does it',['../led__driver_8c.html#autotoc_md49',1,'are currently on in normal state will do it, mode 1 = every single LED does it'],['../led__driver_8c.html#autotoc_md117',1,'are currently on in normal state will do it, mode 1 = every single LED does it)']]],
  ['at_20a_20coord_20and_20use_20render_5fval_27',['Unpack the params inside a knob at a coord and use render_val.',['../led__driver_8c.html#autotoc_md65',1,'']]],
  ['at_20once_28',['Sets a whole channel&apos;s button LEDs at once',['../led__driver_8c.html#autotoc_md81',1,'']]],
  ['at_20top_29',['PUBLIC led_print_config : Debug mode only, print the current configuration params defined at top.',['../led__driver_8c.html#autotoc_md107',1,'']]]
];
