var searchData=
[
  ['that_20show_20that_20value_0',['Directly render: turns a knob&apos;s value into the set of bits that show that value',['../led__driver_8c.html#autotoc_md63',1,'']]],
  ['that_20value_1',['Directly render: turns a knob&apos;s value into the set of bits that show that value',['../led__driver_8c.html#autotoc_md63',1,'']]],
  ['the_20animation_20matches_20the_20mode_2',['center mode the animation matches the mode.',['../led__driver_8c.html#autotoc_md115',1,'']]],
  ['the_20brightness_20of_20all_20leds_20externally_3',['PUBLIC led_brightness : Set the brightness of all LEDs externally.',['../led__driver_8c.html#autotoc_md101',1,'']]],
  ['the_20current_20brightness_20setting_200_20255_4',['PUBLIC led_get_brightness : Returns the current brightness setting 0-255',['../led__driver_8c.html#autotoc_md91',1,'']]],
  ['the_20current_20configuration_20params_20defined_20at_20top_5',['PUBLIC led_print_config : Debug mode only, print the current configuration params defined at top.',['../led__driver_8c.html#autotoc_md107',1,'']]],
  ['the_20display_20mode_20knob_5fscale_5ft_20type_20of_20a_20specified_20knob_6',['PUBLIC knob_get_disp : returns the display mode (knob_scale_t type) of a specified knob',['../led__driver_8c.html#autotoc_md85',1,'']]],
  ['the_20mode_7',['center mode the animation matches the mode.',['../led__driver_8c.html#autotoc_md115',1,'']]],
  ['the_20params_20inside_20a_20knob_20at_20a_20coord_20and_20use_20render_5fval_8',['Unpack the params inside a knob at a coord and use render_val.',['../led__driver_8c.html#autotoc_md65',1,'']]],
  ['the_20scale_20mode_20knob_5fscale_5ft_20type_20of_20a_20specified_20knob_9',['PUBLIC knob_get_scale : returns the scale mode (knob_scale_t type) of a specified knob',['../led__driver_8c.html#autotoc_md87',1,'']]],
  ['the_20set_20of_20bits_20that_20show_20that_20value_10',['Directly render: turns a knob&apos;s value into the set of bits that show that value',['../led__driver_8c.html#autotoc_md63',1,'']]],
  ['the_20specified_20button_20led_20is_20off_20or_20on_11',['Returns whether the specified button LED is off or on.',['../led__driver_8c.html#autotoc_md89',1,'']]],
  ['the_20value_20of_20specified_20knob_12',['PUBLIC knob_get : returns the value of specified knob',['../led__driver_8c.html#autotoc_md83',1,'']]],
  ['them_20out_13',['Range checks external knob/channel coords and copies them out',['../led__driver_8c.html#autotoc_md67',1,'']]],
  ['things_20to_20console_20every_20time_20stuff_20happens_14',['PUBLIC led_debug : Toggle debug mode, it basically just dumps things to console every time stuff happens',['../led__driver_8c.html#autotoc_md105',1,'']]],
  ['time_20on_20pwm_15',['OE is active low so higher brightness needs less high time on PWM.',['../led__driver_8c.html#autotoc_md99',1,'']]],
  ['time_20stuff_20happens_16',['PUBLIC led_debug : Toggle debug mode, it basically just dumps things to console every time stuff happens',['../led__driver_8c.html#autotoc_md105',1,'']]],
  ['timer_17',['PUBLIC led_init : Call once during setup, initializes LED serial pins, PWM timer',['../led__driver_8c.html#autotoc_md103',1,'']]],
  ['to_20a_20knob_20in_20frame_20buffer_18',['PUBLIC knob_raw : Put arbitrary 32 bits to a knob in frame buffer',['../led__driver_8c.html#autotoc_md77',1,'']]],
  ['to_20console_20every_20time_20stuff_20happens_19',['PUBLIC led_debug : Toggle debug mode, it basically just dumps things to console every time stuff happens',['../led__driver_8c.html#autotoc_md105',1,'']]],
  ['to_20leds_20only_20if_20frame_20has_20been_20changed_20dirty_20',['pushing changes to LEDs only if frame has been changed &quot;dirty&quot;',['../led__driver_8c.html#autotoc_md93',1,'']]],
  ['to_20off_20and_20latch_21',['PUBLIC led_clear : Set all led states to off and latch',['../led__driver_8c.html#autotoc_md97',1,'']]],
  ['to_20right_20or_20center_20pan_22',['PUBLIC knob_scale : set scale mode of knob (left to right or center/pan)',['../led__driver_8c.html#autotoc_md75',1,'']]],
  ['to_20update_20leds_23',['INTERNAL latch_out : Pulse latch low to update LEDs',['../led__driver_8c.html#autotoc_md59',1,'']]],
  ['toggle_20debug_20mode_20it_20basically_20just_20dumps_20things_20to_20console_20every_20time_20stuff_20happens_24',['PUBLIC led_debug : Toggle debug mode, it basically just dumps things to console every time stuff happens',['../led__driver_8c.html#autotoc_md105',1,'']]],
  ['top_25',['PUBLIC led_print_config : Debug mode only, print the current configuration params defined at top.',['../led__driver_8c.html#autotoc_md107',1,'']]],
  ['turns_20a_20knob_20s_20value_20into_20the_20set_20of_20bits_20that_20show_20that_20value_26',['Directly render: turns a knob&apos;s value into the set of bits that show that value',['../led__driver_8c.html#autotoc_md63',1,'']]],
  ['type_20of_20a_20specified_20knob_27',['type of a specified knob',['../led__driver_8c.html#autotoc_md85',1,'PUBLIC knob_get_disp : returns the display mode (knob_scale_t type) of a specified knob'],['../led__driver_8c.html#autotoc_md87',1,'PUBLIC knob_get_scale : returns the scale mode (knob_scale_t type) of a specified knob']]]
];
