var searchData=
[
  ['s_20button_20leds_20at_20once_0',['Sets a whole channel&apos;s button LEDs at once',['../led__driver_8c.html#autotoc_md81',1,'']]],
  ['s_20display_20value_1',['Incerment/decrement a knob&apos;s display value.',['../led__driver_8c.html#autotoc_md71',1,'']]],
  ['s_20display_20value_20specify_20which_20knob_20by_20coords_20chnl_20and_20knob_20number_2',['Change a knob&apos;s display value, specify which knob by coords (chnl and knob number)',['../led__driver_8c.html#autotoc_md69',1,'']]],
  ['s_20value_20into_20the_20set_20of_20bits_20that_20show_20that_20value_3',['Directly render: turns a knob&apos;s value into the set of bits that show that value',['../led__driver_8c.html#autotoc_md63',1,'']]],
  ['scale_20mode_20knob_5fscale_5ft_20type_20of_20a_20specified_20knob_4',['PUBLIC knob_get_scale : returns the scale mode (knob_scale_t type) of a specified knob',['../led__driver_8c.html#autotoc_md87',1,'']]],
  ['scale_20mode_20of_20knob_20left_20to_20right_20or_20center_20pan_5',['PUBLIC knob_scale : set scale mode of knob (left to right or center/pan)',['../led__driver_8c.html#autotoc_md75',1,'']]],
  ['sends_20an_20entire_20frame_20of_20led_20bits_20out_20end_20sent_20first_6',['INTERNAL frame_out : Sends an entire frame of LED bits out, end sent first',['../led__driver_8c.html#autotoc_md61',1,'']]],
  ['sent_20first_7',['INTERNAL frame_out : Sends an entire frame of LED bits out, end sent first',['../led__driver_8c.html#autotoc_md61',1,'']]],
  ['serial_20led_20out_20clock_8',['INTERNAL wait_half : Count half cycle of serial LED out clock',['../led__driver_8c.html#autotoc_md55',1,'']]],
  ['serial_20pins_20pwm_20timer_9',['PUBLIC led_init : Call once during setup, initializes LED serial pins, PWM timer',['../led__driver_8c.html#autotoc_md103',1,'']]],
  ['set_20a_20specific_20button_20display_20led_20by_20coordinate_10',['Set a specific button display LED by coordinate',['../led__driver_8c.html#autotoc_md79',1,'']]],
  ['set_20all_20led_20states_20to_20off_20and_20latch_11',['PUBLIC led_clear : Set all led states to off and latch',['../led__driver_8c.html#autotoc_md97',1,'']]],
  ['set_20display_20mode_20of_20knob_12',['PUBLIC knob_disp : Set display mode of knob',['../led__driver_8c.html#autotoc_md73',1,'']]],
  ['set_20of_20bits_20that_20show_20that_20value_13',['Directly render: turns a knob&apos;s value into the set of bits that show that value',['../led__driver_8c.html#autotoc_md63',1,'']]],
  ['set_20scale_20mode_20of_20knob_20left_20to_20right_20or_20center_20pan_14',['PUBLIC knob_scale : set scale mode of knob (left to right or center/pan)',['../led__driver_8c.html#autotoc_md75',1,'']]],
  ['set_20the_20brightness_20of_20all_20leds_20externally_15',['PUBLIC led_brightness : Set the brightness of all LEDs externally.',['../led__driver_8c.html#autotoc_md101',1,'']]],
  ['sets_20a_20whole_20channel_20s_20button_20leds_20at_20once_16',['Sets a whole channel&apos;s button LEDs at once',['../led__driver_8c.html#autotoc_md81',1,'']]],
  ['setting_200_20255_17',['PUBLIC led_get_brightness : Returns the current brightness setting 0-255',['../led__driver_8c.html#autotoc_md91',1,'']]],
  ['setup_20initializes_20led_20serial_20pins_20pwm_20timer_18',['PUBLIC led_init : Call once during setup, initializes LED serial pins, PWM timer',['../led__driver_8c.html#autotoc_md103',1,'']]],
  ['shift_5fbit_20_3a_20uint32_20shifts_20a_20single_20bit_20out_19',['INTERNAL shift_bit : uint32 -&amp;gt; Shifts a single bit out.',['../led__driver_8c.html#autotoc_md57',1,'']]],
  ['shifts_20a_20single_20bit_20out_20',['INTERNAL shift_bit : uint32 -&amp;gt; Shifts a single bit out.',['../led__driver_8c.html#autotoc_md57',1,'']]],
  ['show_20that_20value_21',['Directly render: turns a knob&apos;s value into the set of bits that show that value',['../led__driver_8c.html#autotoc_md63',1,'']]],
  ['single_20bit_20out_22',['INTERNAL shift_bit : uint32 -&amp;gt; Shifts a single bit out.',['../led__driver_8c.html#autotoc_md57',1,'']]],
  ['single_20led_20does_20it_23',['single LED does it',['../led__driver_8c.html#autotoc_md49',1,'are currently on in normal state will do it, mode 1 = every single LED does it'],['../led__driver_8c.html#autotoc_md117',1,'are currently on in normal state will do it, mode 1 = every single LED does it)']]],
  ['so_20higher_20brightness_20needs_20less_20high_20time_20on_20pwm_24',['OE is active low so higher brightness needs less high time on PWM.',['../led__driver_8c.html#autotoc_md99',1,'']]],
  ['specific_20button_20display_20led_20by_20coordinate_25',['Set a specific button display LED by coordinate',['../led__driver_8c.html#autotoc_md79',1,'']]],
  ['specified_20button_20led_20is_20off_20or_20on_26',['Returns whether the specified button LED is off or on.',['../led__driver_8c.html#autotoc_md89',1,'']]],
  ['specified_20knob_27',['specified knob',['../led__driver_8c.html#autotoc_md83',1,'PUBLIC knob_get : returns the value of specified knob'],['../led__driver_8c.html#autotoc_md85',1,'PUBLIC knob_get_disp : returns the display mode (knob_scale_t type) of a specified knob'],['../led__driver_8c.html#autotoc_md87',1,'PUBLIC knob_get_scale : returns the scale mode (knob_scale_t type) of a specified knob']]],
  ['specify_20which_20knob_20by_20coords_20chnl_20and_20knob_20number_28',['Change a knob&apos;s display value, specify which knob by coords (chnl and knob number)',['../led__driver_8c.html#autotoc_md69',1,'']]],
  ['state_20will_20do_20it_20mode_201_20every_20single_20led_20does_20it_29',['state will do it mode 1 every single LED does it',['../led__driver_8c.html#autotoc_md49',1,'are currently on in normal state will do it, mode 1 = every single LED does it'],['../led__driver_8c.html#autotoc_md117',1,'are currently on in normal state will do it, mode 1 = every single LED does it)']]],
  ['states_20to_20off_20and_20latch_30',['PUBLIC led_clear : Set all led states to off and latch',['../led__driver_8c.html#autotoc_md97',1,'']]],
  ['stop_20and_20call_20anim_5fstop_31',['When loading done just stop and call anim_stop.',['../led__driver_8c.html#autotoc_md113',1,'']]],
  ['stop_20what_20was_20running_20and_20claim_20display_32',['PUBLIC anim_claim : stop what was running and claim display',['../led__driver_8c.html#autotoc_md111',1,'']]],
  ['stuff_20happens_33',['PUBLIC led_debug : Toggle debug mode, it basically just dumps things to console every time stuff happens',['../led__driver_8c.html#autotoc_md105',1,'']]]
];
