/**
  **********************************************************************************
  * I2C SCHEDULER HEADER - DIGILOG CONSOLE
  **********************************************************************************
  * @file i2c_scheduler.h
  * @brief Entry point for one frame of the I2C schedule. The schedule itself is specified in
  *        the header comment block of i2c_driver.h.
  *
  * @author Darya Petrova (petrov.da@northeastern.edu)
  *
  * @note Doc banner generated by Claude (Opus 5) from the source at `cc3d3a1`; not
  *       author-written and not yet author-reviewed. Code authorship is unchanged.
  *       Delete this note once an author has reviewed it.
  **********************************************************************************
*/
#ifndef I2C_SCHEDULER_H
#define I2C_SCHEDULER_H

#include <stdint.h>

/**
 * @brief Start a single frame of the I2C communication for the given bucket channel
 */
void start_i2c_frame (uint8_t channel);

#endif
