/**
  **********************************************************************************
  * I2C SCHEDULER HEADER - DIGILOG CONSOLE
  **********************************************************************************
  * @file i2c_scheduler.h
  * @brief Public interface to the I2C scheduler: init_i2c_scheduler() creates the four bus
  *        tasks and starts TIM4; i2c_scheduler_trigger_frame() is called from the TIM4
  *        interrupt. The schedule itself is specified in the header comment block of
  *        i2c_driver.h.
  *
  * @author Darya Petrova (petrov.da@northeastern.edu)
  *
  * @note Doc banner generated by Claude (Opus 5; revised by Opus 5.5) from the source at `ff59558`.
  *       Not author-written and not yet author-reviewed; code authorship is
  *       unchanged. Delete this note once an author has reviewed it.
  **********************************************************************************
*/
#ifndef I2C_SCHEDULER_H
#define I2C_SCHEDULER_H

/**
 * @brief Initialize I2C Scheduler timer and tasks
 */
void init_i2c_scheduler (void);

/**
 * @brief Trigger one frame of the I2C scheduler on all channels
 */
void i2c_scheduler_trigger_frame (void);


#endif
