/**
  **********************************************************************************
  * BUTTON DRIVER HEADER - DIGILOG CONSOLE
  **********************************************************************************
  * @file button_driver.h
  * @brief Reads one push button's level out of the MCP23017 cache. Touches no bus: the
  *        cache is filled separately by mcp23017_poll_to_cache().
  *
  * @author Darya Petrova (petrov.da@northeastern.edu)
  *
  * @note Doc banner generated by Claude (Opus 5) from the source at `6aa52bb`; not
  *       author-written and not yet author-reviewed. Code authorship is unchanged.
  *       Delete this note once an author has reviewed it.
  **********************************************************************************
*/
#ifndef BUTTON_DRIVER_H
#define BUTTON_DRIVER_H

#include "hardware_drivers/mcp23017.h"
#include "stm32g474xx.h"

/**
 * @brief Info on the location of a single button
 */
typedef struct
{
    I2C_TypeDef *bus;  //!< I2C bus of the gpio expander which the button is connected to
    uint8_t addr;      //!< I2C address of the gpio expander
    MCP23017_Reg port; //!< Register/Port on the MCP23017 that the button pin is on;
    uint8_t pin;       //!< Pin which the button output is connected to
} button_info_t;

/**
 * @brief Get the current hold state of a button based on cached MCP23017 values
 */
bool get_button_state (button_info_t *info);

#endif
