/**
  **********************************************************************************
  * MOTORIZED FADER DRIVER HEADER - DIGILOG CONSOLE
  **********************************************************************************
  * @file fader_driver.h
  * @brief Types and entry point for the motorized faders (Alps RSA0N11M9). Position sense,
  *        touch sense and H-bridge motor drive.
  *
  * @warning Incomplete. fader_info_t is an empty struct, and the driver's hardware
  *          primitives are unimplemented - see fader_driver.c.
  *
  * @author Darya Petrova (petrov.da@northeastern.edu)
  *
  * @note Doc banner generated by Claude (Opus 5) from the source at `6aa52bb`; not
  *       author-written and not yet author-reviewed. Code authorship is unchanged.
  *       Delete this note once an author has reviewed it.
  **********************************************************************************
*/
#ifndef FADER_DRIVER_H
#define FADER_DRIVER_H

#include <stdint.h>
#include "stm32g474xx.h"
#include "stm32g4xx_ll_adc.h"

#define DEFAULT_FADER_STATE (fader_state_t){.movement_mode = FADER_UNPOWERED, .position = UINT16_MAX / 2}

/**
 * @brief Hardware connection info of the fader
 */
typedef struct
{
    GPIO_TypeDef *touch_sensor_port;
    uint8_t touch_sensor_pin;

    GPIO_TypeDef *motor_a_port;
    uint8_t motor_a_pin;
    GPIO_TypeDef *motor_b_port;
    uint8_t motor_b_pin;

    ADC_HandleTypeDef *adc;
    uint32_t adc_channel;
} fader_info_t;

typedef enum
{
    FADER_UNPOWERED,           //!< Allow free motion to drive position (active when touch detected)
    FADER_MOVE_OR_HOLD_TARGET, //!< Move to or hold a driven position
} fader_movement_mode_state;

typedef struct
{
    fader_movement_mode_state movement_mode;
    uint16_t position;
} fader_state_t;

// TODO: maybe add calibration options to state (i.e lower and upper values)

/**
 * @brief Updates a fader state based on physical behavior, or a fader's physical behavior based on its state
 */
void update_fader (
    fader_info_t *info,       //!< Hardware connection info of the fader
    fader_state_t *old_state, //!< Pointer to the old fader state containing its last polled values
    fader_state_t *new_state  //!< Pointer in which to store the new fader state
);

/**
 * @brief initialize hardware as necessary for the given fader
 */
void init_fader(fader_info_t *info);

#endif
