name: Deploy Doxygen to GitHub Pages

on:
  push:
    branches:
      - main # Change to master if needed

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Bypass Jekyll
        run: touch Firmware_Documentation/html/.nojekyll # Replaces 'html' with your specific HTML_OUTPUT folder if changed

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html # The folder where Doxygen generated the HTML files
          branch: gh-pages # The branch the action will deploy to
